networks:
  easyshell:
    external: true

services:
  queue-processor:
    build:
      context: .
      dockerfile: ./apps/queue-processor/Dockerfile
    container_name: easyshell-dev-queue-processor
    volumes:
      - /tmp/easyshell:/tmp/easyshell
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - easyshell
    environment:
      APP: queue-processor
      DATABASE_URL: ${DATABASE_URL}
  session-manager:
    build:
      context: ./apps/session-manager
    container_name: easyshell-dev-session-manager
    networks:
      - easyshell
    ports:
      - 4000:4000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
