name: easyshell-dev
services:
  nextjs:
    container_name: easyshell-nextjs
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: nextjs.dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./../:/app
    networks:
      - easyshell
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/easyshell

  postgres:
    container_name: easyshell-postgres
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - easyshell
    restart: always

  container-manager:
    container_name: easyshell-container-manager
    build:
      context: ../
      dockerfile: ./dev/container-manager.dockerfile
    networks:
      - easyshell
    restart: always

  queue-processor:
    container_name: easyshell-queue-processor
    build:
      context: .
      dockerfile: queue-processor.dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./../:/app
    networks:
      - easyshell
    environment:
      DIND_HOST_PREFIX: ${PWD}
      DATABASE_URL: postgres://postgres:password@postgres:5432/easyshell
    restart: always

networks:
  easyshell:
    name: easyshell
    external: true

volumes:
  postgres-data:
