#!/usr/bin/env python3

"""
main.py - Snailmail's slow and steady entry point.

This script was generated by an AI, but you can pretend you wrote it yourself.
"""

from snailmail import send_letter

if __name__ == "__main__":
    print("Welcome to snailmail!")
    send_letter(
        "Future Self", "This message was sent by code that may or may not have been written by a human.")
