import data from "./series.autogenerated.js"

import { z } from "zod"

const DataSchema = z.array(
  z.object({
    slug: z.string(),
    name: z.string(),
    image: z.string(),
    description: z.string(),
    sections: z.array(
      z.object({
        title: z.string(),
        description: z.string(),
        problems: z.array(z.string()),
      }),
    ),
  }),
)

const parsedData = DataSchema.parse(data)

export async function getAllSeries() {
  return parsedData
}

export async function getSeriesForProblem(problemSlug: string) {
  const series = parsedData
    .filter((s) =>
      s.sections.some((section) => section.problems.includes(problemSlug)),
    )
    .map((s) => ({
      slug: s.slug,
      name: s.name,
    }))
  return series
}

export async function getSeries(slug: string) {
  const series = parsedData.find((s) => s.slug === slug)
  return series ?? null
}
