name: deploy problem (move-and-rename)
on:
  push:
    branches:
      - main
    paths:
      - "packages/problems/move-and-rename/**"

concurrency:
  group: deploy-move-and-rename
  cancel-in-progress: false

jobs:
  deploy:
    needs:
      - test-entrypoint
      - test-tsc
    environment: deployment
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - uses: actions/checkout@v4
      - run: npm i
      - run: npm run build move-and-rename
        name: build problem
        working-directory: ./packages/problems
      - run: npm run test move-and-rename
        name: test problem
        working-directory: ./packages/problems
      - run: npm run build move-and-rename
        name: push problem
        working-directory: ./packages/problems
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
