name: test problem (move-that-file)

on:
  pull_request:
    paths:
      - "packages/problems/move-that-file/**"

jobs:
  test:
    needs:
      - test-entrypoint
      - test-tsc
    runs-on: ubuntu-latest
    environment: linting
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - run: npm i
        name: Install dependencies
      - run: npm run build move-that-file
        working-directory: ./packages/problems
      - run: npm run test move-that-file
        working-directory: ./packages/problems
