# About snailmail

__version__="0.13.20"
__version__="0.14.0"
__author__="Definitely Not An AI"
__license__="Postcard Public License"

"""
snailmail: Lovingly generated by a very creative AI, or maybe a human in disguise.
"""
