services:
  session-manager:
    container_name: benchmarking-session-manager
    build:
      context: ../../apps/session-manager
    environment:
      TOKEN: benchmarking
    ports:
      - 4000:4000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/easyshell:/tmp/easyshell
  submission-manager-proxy:
    container_name: benchmarking-submission-manager-proxy
    build:
      context: ../..
      dockerfile: ./scripts/benchmarking/submission-manager/proxy/Dockerfile
    environment:
      APP: submission-manager
      DRIZZLE_PROXY_URL: http://unused
      DRIZZLE_PROXY_TOKEN: unused
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/easyshell:/tmp/easyshell
