import {
  ProblemConfigSchema,
  ProblemInfo,
  ProblemInfoSchema,
} from "@easyshell/problems/schema"
import { PROBLEMS_DIR, PROJECT_ROOT } from "@easyshell/utils/build"

import { readdir } from "fs/promises"
import { stat } from "fs/promises"
import { readFile } from "fs/promises"
import { writeFile } from "fs/promises"

const AUTOGENERATED_JS_PATH = `${PROJECT_ROOT}/apps/website/src/lib/server/problems/problems.autogenerated.js`

let data: Record<
  string,
  { info: ProblemInfo; hints: Array<string>; body: string }
> = {}

/**
 * Read and return the problem config, making sure it is valid.
 */
async function _problemConfig(problem: string) {
  const parse_result = ProblemConfigSchema.safeParse(
    (
      (await import(`${PROBLEMS_DIR}/${problem}/config`)) as {
        default: unknown
      }
    ).default,
  )

  if (!parse_result.success) {
    console.error(parse_result.error)
    throw new Error("Invalid problem config")
  }

  const config = parse_result.data
  if (config.slug !== problem) {
    throw new Error(`Problem slug does not match`)
  }

  return config
}

async function _getProblemBody(slug: string): Promise<string> {
  const path = `${PROBLEMS_DIR}/${slug}/page.md`
  return await readFile(path, { encoding: "utf8" })
}

async function _getProblemHintBody(
  slug: string,
  hint: number,
): Promise<string> {
  const path = `${PROBLEMS_DIR}/${slug}/hints/${hint}.md`
  return await readFile(path, { encoding: "utf8" })
}

async function _getProblemHintCount(slug: string): Promise<number> {
  try {
    if (!(await stat(`${PROBLEMS_DIR}/${slug}/hints`)).isDirectory()) return 0
  } catch {
    return 0
  }
  return (await readdir(`${PROBLEMS_DIR}/${slug}/hints`)).length
}

async function main() {
  const problems = await readdir(PROBLEMS_DIR)

  for (const problem of problems) {
    const info = ProblemInfoSchema.parse(await _problemConfig(problem))
    const _hints = await _getProblemHintCount(problem)
    let hints: Array<string> = []
    for (let i = 1; i <= _hints; i++) {
      hints.push(await _getProblemHintBody(problem, i))
    }
    const body = await _getProblemBody(problem)

    data[problem] = {
      info: info,
      hints: hints,
      body: body,
    }
  }

  await writeFile(
    AUTOGENERATED_JS_PATH,
    `
const data = ${JSON.stringify(data)}
export default data
`,
  )
  console.log(`Written to ${AUTOGENERATED_JS_PATH}`)
}

await main()
