import { PROBLEMS_DIR, PROJECT_ROOT } from "@easyshell/utils/build"

import { $ } from "execa"
import { readdir } from "fs/promises"
import { writeFile } from "fs/promises"

const WORKFLOWS_DIR = `${PROJECT_ROOT}/.github/workflows`

export function autogeneratedWorkflowPath({
  suffix,
  type,
}: {
  suffix: string
  type: "deploy" | "test"
}) {
  if (type === "deploy") {
    return `${WORKFLOWS_DIR}/autogenerated-deploy-${suffix}.yml`
  } else if (type === "test") {
    return `${WORKFLOWS_DIR}/autogenerated-test-${suffix}.yml`
  }
  throw new Error("Invalid type")
}

function generateTestWorkflow(problemSlug: string): string {
  return `\
name: test problem (${problemSlug})

on:
  pull_request:
    paths:
      - "packages/problems/data/problems/${problemSlug}/**"
      - "packages/env/**"
      - "packages/utils/**"
      - "packages/queue-processor/**"

jobs:
  test:
    runs-on: ubuntu-latest
    environment: linting
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - run: npm ci
        name: Install dependencies
      - run: npm run build ${problemSlug}
        working-directory: ./packages/problems
      - run: npm run test ${problemSlug}
        working-directory: ./packages/problems
`
}

function generateDeployWorkflow(problemSlug: string): string {
  return `\
name: deploy problem (${problemSlug})
on:
  push:
    branches:
      - main
    paths:
      - "packages/problems/data/problems/${problemSlug}/**"
      - "packages/env/**"
      - "packages/utils/**"
      - "packages/queue-processor/**"

concurrency:
  group: deploy-${problemSlug}
  cancel-in-progress: false

jobs:
  deploy:
    environment: deployment
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: \${{ secrets.DOCKER_REGISTRY }}
          username: \${{ secrets.DOCKER_USERNAME }}
          password: \${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build ${problemSlug}
        name: build problem
        working-directory: ./packages/problems
      - run: npm run test ${problemSlug}
        name: test problem
        working-directory: ./packages/problems
      - run: npm run push ${problemSlug}
        name: push problem
        working-directory: ./packages/problems
        env:
          DOCKER_REGISTRY: \${{ secrets.DOCKER_REGISTRY }}
`
}

async function main() {
  await $`rm -rf ${WORKFLOWS_DIR}/autogenerated-*`

  const problems = await readdir(PROBLEMS_DIR)

  for (const problem of problems) {
    const deploy_workflow_path = autogeneratedWorkflowPath({
      suffix: problem,
      type: "deploy",
    })
    const deploy_workflow = generateDeployWorkflow(problem)
    await writeFile(deploy_workflow_path, deploy_workflow)

    const test_workflow_path = autogeneratedWorkflowPath({
      suffix: problem,
      type: "test",
    })
    const test_workflow = generateTestWorkflow(problem)
    await writeFile(test_workflow_path, test_workflow)
  }
}

await main()
