// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
  NEXTJS_ENV: string
  DISCORD_CLIENT_ID: string
  DISCORD_CLIENT_SECRET: string
  NEXTAUTH_SECRET: string
  GITHUB_CLIENT_ID: string
  GITHUB_CLIENT_SECRET: string
  GOOGLE_CLIENT_ID: string
  GOOGLE_CLIENT_SECRET: string
  NEXTAUTH_URL: string
  DATABASE_URL: string
  SESSION_MANAGER_URL: string
  APP: string
  ASSETS: Fetcher
  NEXT_PUBLIC_POSTHOG_HOST: string
  NEXT_PUBLIC_POSTHOG_KEY: string
  RESEND_API_KEY: string
}
