// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
  NEXTJS_ENV: string
  DISCORD_CLIENT_ID: string
  DISCORD_CLIENT_SECRET: string
  NEXTAUTH_SECRET: string
  GITHUB_CLIENT_ID: string
  GITHUB_CLIENT_SECRET: string
  GOOGLE_CLIENT_ID: string
  GOOGLE_CLIENT_SECRET: string
  NEXTAUTH_URL: string
  DATABASE_URL: string
  CONTAINER_MANAGER_URL: string
  APP: string
  ASSETS: Fetcher
}
