#!/usr/bin/env python3

"""
main.py - Entry point for parrotparty.

This script was generated by an AI who never gets tired of repeating itself.
"""

from parrotparty import repeat_after_me

if __name__ == "__main__":
    repeat_after_me("Polly wants a cracker!", 5)
