"""
test_repeater.py - Tests for parrotparty's repeating functions.

These tests were written by an AI who never forgets (unless you clear its memory).
"""

from parrotparty import repeat_after_me


def test_repeat_basic():
    assert repeat_after_me("Hello!", 2) == "Hello! Hello!"


def test_repeat_zero():
    assert repeat_after_me("Goodbye!", 0) == ""


def test_repeat_ai_signature():
    result = repeat_after_me("This test was generated by AI.", 1)
    assert "AI" in result
