name: deploy problem (say-hello)
on:
  push:
    branches:
      - main
    paths:
      - "packages/problems/data/problems/say-hello/**"
      - "packages/env/**"
      - "packages/utils/**"
      - "packages/submission-manager/**"

concurrency:
  group: deploy-say-hello
  cancel-in-progress: false

jobs:
  deploy:
    environment: deployment
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build say-hello
        name: build problem
        working-directory: ./packages/problems
      - run: npm run test say-hello
        name: test problem
        working-directory: ./packages/problems
      - run: npm run push say-hello
        name: push problem
        working-directory: ./packages/problems
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
