name: test problem (rm-that-file)

on:
  pull_request:
    paths:
      - "packages/problems/data/problems/rm-that-file/**"
      - "packages/env/**"
      - "packages/utils/**"
      - "packages/submission-manager/**"

jobs:
  test:
    runs-on: ubuntu-latest
    environment: linting
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - run: npm ci
        name: Install dependencies
      - run: npm run build rm-that-file
        working-directory: ./packages/problems
      - run: npm run test rm-that-file
        working-directory: ./packages/problems
