name: deploy problem (bulk-move)
on:
  push:
    branches:
      - main
    paths:
      - "packages/problems/data/problems/bulk-move/**"
      - "packages/env/**"
      - "packages/utils/**"
      - "packages/submission-manager/**"

concurrency:
  group: deploy-bulk-move
  cancel-in-progress: false

jobs:
  deploy:
    environment: deployment
    runs-on: ubuntu-latest
    steps:
      - name: tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build bulk-move
        name: build problem
        working-directory: ./packages/problems
      - run: npm run test bulk-move
        name: test problem
        working-directory: ./packages/problems
      - run: npm run push bulk-move
        name: push problem
        working-directory: ./packages/problems
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
