name: test problem (get-it-curl)

on:
  pull_request:
    paths:
      - "packages/problems/data/problems/get-it-curl/**"
      - "packages/env/**"
      - "packages/utils/**"
      - "packages/submission-manager/**"

jobs:
  test:
    runs-on: ubuntu-latest
    environment: linting
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - run: npm ci
        name: Install dependencies
      - run: npm run build get-it-curl
        working-directory: ./packages/problems
      - run: npm run test get-it-curl
        working-directory: ./packages/problems
