name: test problem (bulk-move)

on:
  pull_request:
    paths:
      - "packages/problems/data/problems/bulk-move/**"
      - "packages/env/**"
      - "packages/utils/**"
      - "packages/queue-processor/**"

jobs:
  test:
    runs-on: ubuntu-latest
    environment: linting
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - run: npm ci
        name: Install dependencies
      - run: npm run build bulk-move
        working-directory: ./packages/problems
      - run: npm run test bulk-move
        working-directory: ./packages/problems
