name: Deployment
on:
  push:
    branches:
      - main

concurrency:
  group: deployment
  cancel-in-progress: false

jobs:
  # =========================== Pushing to Registry ============================

  registry-push-problems:
    environment: deployment
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install -y jq
      - run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - uses: oven-sh/setup-bun@v2
      - uses: actions/checkout@v4
      - run: bun i
      - run: bun run build all
        working-directory: ./packages/problems
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          PARALLEL_LIMIT_BUILD: 4
          PARALLEL_LIMIT_PUSH: 10

  registry-push-session-manager:
    environment: deployment
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install -y jq
      - run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - uses: actions/checkout@v4
      - run: docker build -t ${{ secrets.DOCKER_REGISTRY }}/session-manager -f ./apps/session-manager/Dockerfile ./apps/session-manager
      - id: local-digest
        run: echo "::set-output name=local-digest::$(docker image inspect ${{ secrets.DOCKER_REGISTRY }}/session-manager | jq -r '.[0].Id')"
      - id: remote-digest
        run: echo "::set-output name=remote-digest::$(docker manifest inspect ${{ secrets.DOCKER_REGISTRY }}/session-manager | jq -r '.config.digest')"
      - if: steps.local-digest.outputs.local-digest != steps.remote-digest.outputs.remote-digest
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/session-manager:latest

  registry-push-queue-processor:
    environment: deployment
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install -y jq
      - run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - uses: actions/checkout@v4
      - run: docker build -t ${{ secrets.DOCKER_REGISTRY }}/queue-processor -f ./apps/queue-processor/Dockerfile .
      - id: local-digest
        run: echo "::set-output name=local-digest::$(docker image inspect ${{ secrets.DOCKER_REGISTRY }}/queue-processor | jq -r '.[0].Id')"
      - id: remote-digest
        run: echo "::set-output name=remote-digest::$(docker manifest inspect ${{ secrets.DOCKER_REGISTRY }}/queue-processor | jq -r '.config.digest')"
      - if: steps.local-digest.outputs.local-digest != steps.remote-digest.outputs.remote-digest
      - run: docker push ${{ secrets.DOCKER_REGISTRY }}/queue-processor:latest

  # ============================================================================

  # =============================== Deployments ================================

  deploy-vps:
    needs:
      - registry-push-problems
      - registry-push-queue-processor
      - registry-push-session-manager
    environment: deployment
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Make .ssh folder
        run: mkdir -p ~/.ssh
      - name: Write SSH private key
        run: echo '${{ secrets.SSH_PRIVATE_KEY }}' > ~/.ssh/id_rsa
      - name: Set permissions for SSH private key
        run: chmod 400 ~/.ssh/id_rsa
      - name: SSH into server
        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} './scripts/update-easyshell.sh'

  deploy-cf:
    environment: deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run cache:website
        working-directory: ./packages/problems
      - run: npm run deploy
        working-directory: ./apps/website
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

  # ============================================================================
