name: Deploy Problems

on:
  workflow_dispatch:
    inputs:
      problem:
        description: "Problem to deploy"
        required: true
        default: "all"
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - name: tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - run: npm ci
        name: Install dependencies
      - run: npm run build ${{ inputs.problem }}
        name: build
        working-directory: ./packages/problems
      - run: npm run test ${{ inputs.problem }}
        name: test
        working-directory: ./packages/problems
      - run: npm run push ${{ inputs.problem }}
        name: push
        working-directory: ./packages/problems
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
