name: deploy website
on:
  push:
    branches:
      - main
    paths:
      - "packages/**"
      - "apps/website/**"
  workflow_dispatch:

concurrency:
  group: deployment
  cancel-in-progress: false

jobs:
  deploy-website:
    needs:
      - test-tsc
    environment: deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run cache:website
        working-directory: ./packages/problems
      - run: npm run deploy
        working-directory: ./apps/website
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
