name: Test Problems

on:
  push:
    branches:
      - main
    paths:
      - "problems/**"
  pull_request:
    paths:
      - "problems/**"

jobs:
  test:
    runs-on: ubuntu-latest
    environment: linting
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun i
      - run: bun problems:lint
    env:
      SKIP_ENV_VALIDATION: 1
