name: Test TypeScript Files

on:
  push:
    branches:
      - main
    paths: 
      - "**/*.js"
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.jsx"
      - "**/*.cjs"
  pull_request:
    paths: 
      - "**/*.js"
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.jsx"
      - "**/*.cjs"

jobs:
  test:
    runs-on: ubuntu-latest
    environment: linting
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun i
        name: Install dependencies
      - run: bunx tsc --noEmit
        name: Check TypeScript types
      - run: bun next:lint
        name: Lint Next.js files
      - run: bun prettier:check
        name: Check Formatting
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
      DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
